### ISSUE TITLE
[ CREATE ] - Navbar

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Keiko-Corp#1]
Create a navbar similar to the one below:

![image](https://user-images.githubusercontent.com/6190356/94612960-c304f300-029b-11eb-8616-90f800c7a550.png)

# IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING

**Comment by leonarhv** [comment]
I want to Claim this task. I will start right away

**Comment by leonarhv** [comment]
# Update on the task
I started the project with the main part based on the mock layout. Later today i will finish the navbar and work on responsivity


<img width="1085" alt="navbar" src="https://user-images.githubusercontent.com/53581258/94769517-9bd81f80-0388-11eb-9c55-e68661418aaa.png">

**Comment by subho2107** [comment]
@MattCSmith can i work on this?

**Comment by tttyyy1456** [comment]
Will do a navbar

**Comment by MattCSmith** [comment]
@subho2107 Its already being worked on. I will be creating more tasks shortly, however feel free to create your own task.

**Comment by leonarhv** [comment]
## Update 2
I will just do the js part and then do the pull request :)

<img width="303" alt="Captura de tela 2020-10-01 135040" src="https://user-images.githubusercontent.com/53581258/94839259-1f2b5c80-03ed-11eb-88c2-d6c13ff62659.png">
