### ISSUE TITLE
[ CREATE ] - Contact Us Section

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Keiko-Corp#10]
Create the contact us section as detailed below. 
This is a pretty big task, so don't worry to much about getting it perfect. These are things other people can pick up to gain experience. 

![image](https://user-images.githubusercontent.com/6190356/94623170-804b1700-02ab-11eb-8d2b-5ad18cf5c6ab.png)

#### IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING

**Comment by chetas411** [comment]
@MattCSmith claiming on this!

**Comment by chetas411** [comment]
@MattCSmith can you review my PR for this issue?

**Comment by fiona-byte** [comment]
Is this task still open? If yes, I want to work on it

**Comment by chetas411** [comment]
> Is this task still open? If yes, I want to work on it

Sorry but I had already made a pull request for this one today only.

**Comment by MattCSmith** [comment]
> Is this task still open? If yes, I want to work on it

@fiona-byte This one has already been worked on by @chetas411 and was recently merged in.
However the beauty of opensource projects like this, is that we can collaborate together to make something truly awesome. 
If there is anything on the contact page you think could be improved, feel free to create a pull request for it. 

> can you review my PR for this issue?
@chetas411 Nice job 👍
