### ISSUE TITLE
Unnecessary text in the navbar of login page

### ISSUE THREAD

**Issue by stee1ix** [zero-to-mastery/Keiko-Corp#1044]
There is an unnecessary piece of text appearing in the navbar of the login page beside the logo

Here is the screenshot

![Keiko_Corp_nav bar redundant  message](https://user-images.githubusercontent.com/54289882/134038850-9e73b626-22eb-4a9e-8646-7706f1aa4235.png)

**Comment by rishika789** [comment]
I will like to work on this

**Comment by shivprime94** [comment]
I am interested.

**Comment by rushikeshadhav** [comment]
Hii , I will fix this issue. Please assign me.

**Comment by AlcatrazFP** [comment]
Hii, I would like to work on this issue

**Comment by stee1ix** [comment]
well guys, the weird thing here is that, in the code, there is no such thing as seen on the website. On the local machine, it looks fine as well. But only online it shows up like that.
