### ISSUE TITLE
[ CREATE ] - Footer

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Keiko-Corp#11]
Create the footer as using the example below: 
Dont worry about linking the pages for now, we can visit this later once the sections are complete. 
![image](https://user-images.githubusercontent.com/6190356/94623407-023b4000-02ac-11eb-87f9-bec589aa2feb.png)

#### IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING

**Comment by JoshuaCode1** [comment]
I will work on this

**Comment by JoshuaCode1** [comment]
Am through with this task. will push now

**Comment by JoshuaCode1** [comment]
I just did PR for this task

**Comment by brittneypostma** [comment]
@JoshuaCode1 This never got merged in because of a conflict, but I'm looking through it and there are a lot of additions like bootstrap and jquery that aren't needed here. If you want to try pulling the upstream to get the most current version and adding just the footer section back, we can pull this in.

**Comment by krittiyaclark** [comment]
I completed the footer on #207 How do I sync this issue? Thank you for your advice!

**Comment by brittneypostma** [comment]
@krittiyaclark the message when you create the pull requests has a checklist to be completed as seen here:
![image](https://user-images.githubusercontent.com/45889730/94949262-9f65c680-04ae-11eb-98cc-a430b33328c4.png)
These need to be completed and you link it by typing # followed by the number of the issue.

**Comment by brittneypostma** [comment]
Merged
