### ISSUE TITLE
Contact Us page is already present

### ISSUE THREAD

**Issue by chetas411** [zero-to-mastery/Keiko-Corp#114]
There is already a Contact Us page present and [linked](https://keiko-corp.netlify.app/contact.html) but another Contact Us section is incorporated in the landing page itself.
We should remove that section from the landing page as there is already a page linked for it.
I would like to do it.
![image](https://user-images.githubusercontent.com/65273718/94885757-b09edb00-048e-11eb-8807-f32a66ee0890.png)
![image](https://user-images.githubusercontent.com/65273718/94885774-bdbbca00-048e-11eb-82dd-2e01557b3357.png)

**Comment by chetas411** [comment]
@MattCSmith  and @brittneypostma  can you give your opinion on this?

**Comment by brittneypostma** [comment]
I think the idea was to merge it into the index.html in the end, it was just easier for people to work on a file outside of index.html with all the merge conflicts. If we are adding other pages, it may make sense to reevaluate and just have it be pages instead of a spa layout.

**Comment by chetas411** [comment]
> 
> 
> I think the idea was to merge it into the index.html in the end, it was just easier for people to work on a file outside of index.html with all the merge conflicts. If we are adding other pages, it may make sense to reevaluate and just have it be pages instead of a spa layout.

@brittneypostma Yeah I was thinking the same but this another contact section that is present in the landing page itself now is confusing for others, so I guess we should remove it so that there will be a single reference to the Contact Us page and others can work on that only if they wanna improve further?

**Comment by brittneypostma** [comment]
@chetas411 We want the contact page to be consolidated into the homepage and there is another issue open on this. I'm closing this issue for now.
