### ISSUE TITLE
fixing width issue of div of classname[neverMissUpdate].

### ISSUE THREAD

**Issue by armedev** [zero-to-mastery/Keiko-Corp#134]

**Comment by JoshuaCode1** [comment]
on which component is nevermissupdate container? please could you help with visual(screenshot) @armedev

**Comment by armedev** [comment]
> on which component is nevermissupdate container? please could you help with visual(screenshot) @armedev

yes
![Screenshot from 2020-10-02 15-21-16](https://user-images.githubusercontent.com/51921579/94911183-61bf6880-04c3-11eb-9162-e477f74d04ff.png)

**Comment by armedev** [comment]
> on which component is nevermissupdate container? please could you help with visual(screenshot) @armedev

actually, this section has an irrelevant style which results in an x scroll bar.
![Screenshot from 2020-10-02 15-26-15](https://user-images.githubusercontent.com/51921579/94911570-f7f38e80-04c3-11eb-8c32-6e7ea9681b32.png)

**Comment by armedev** [comment]
@MattCSmith and @brittneypostma please review the PR.

**Comment by brittneypostma** [comment]
@armedev the issue needs to be tagged in the pull request. I don't see one linked to this issue.

**Comment by armedev** [comment]
@brittneypostma I recommend merging the pr I submitted as it would be very responsive to use `%` over VW.

**Comment by brittneypostma** [comment]
@armedev I still don't see this issue linked to a pr.

**Comment by brittneypostma** [comment]
I found the pull request, I'm not sure how this is solving a responsive issue though. 100vw takes up the full viewport width, 100% will take up 100% of the parent container. I don't think this aligns with the quality pr that Digital Ocean expects for Hacktoberfest. I am going to close this one out.
