### ISSUE TITLE
Fix some UI issues

### ISSUE THREAD

**Issue by Kvaibhav01** [zero-to-mastery/Keiko-Corp#151]
There are various sections on the homepage where the UI can be improved via CSS styling. Some of these are:

- The hero section.
- The team section (on hover).
- The contact section and more.

I'm working to fix these issues and will create a PR soon.

**Comment by brittneypostma** [comment]
This issue contains too many fixes and will be closed when i merge in the fixed footer section. Try to make small incremental issues that can be fixed.
