### ISSUE TITLE
[Create] Social Media Icons.

### ISSUE THREAD

**Issue by aniketsingh98571** [zero-to-mastery/Keiko-Corp#17]
Creating Social Media Icons for the brand and Linking them. @MattCSmith

**Comment by aniketsingh98571** [comment]
I would Like to work on this issue @MattCSmith

**Comment by MattCSmith** [comment]
@aniketsingh98571 Sounds great, go ahead with this

**Comment by brittneypostma** [comment]
Closing as I believe this issue has been added.
