### ISSUE TITLE
hover issue in call to action button

### ISSUE THREAD

**Issue by armedev** [zero-to-mastery/Keiko-Corp#177]
when you hover over a button the whole section is moving upwards which is quite annoying...

**Comment by karkranikhil** [comment]
let me fix

**Comment by armedev** [comment]
actually, I finished fixing it.

**Comment by armedev** [comment]
don't include package-lock.json

**Comment by armedev** [comment]
@karkranikhil  check this out and submit your review on this.

**Comment by armedev** [comment]
this issue is solved, thank you.
