### ISSUE TITLE
Recreating the footer as per mockup...Currently footer is not according to the design

### ISSUE THREAD

**Issue by pritesh11-10** [zero-to-mastery/Keiko-Corp#194]
I would be giving a shot at it. Will work in parts

**Comment by brittneypostma** [comment]
@pritesh11-10 I commented on the pr, please make sure to pull from the main repo before making changes to fix conflicts.

**Comment by pritesh11-10** [comment]
How can I fix conflicts? can I know what is the reason that caused conflict?
