### ISSUE TITLE
Make a Contact Us section look like the Mockup

### ISSUE THREAD

**Issue by nemo0** [zero-to-mastery/Keiko-Corp#199]
The current Contact Us section doesn't look like the mockup. I am taking this to make it look like the mockup.

**Comment by chetas411** [comment]
The contact Us page has already been implemented , you can check [Contact Us page](https://keiko-corp.netlify.app/contact.html)
You can add this in the homepage though.

**Comment by nemo0** [comment]
> The contact Us page has already been implemented , you can check [Contact Us page](https://keiko-corp.netlify.app/contact.html)
> You can add this in the homepage though.

I am working on the homepage contact us section. Is it okay?

**Comment by chetas411** [comment]
> 
> 
> > The contact Us page has already been implemented , you can check [Contact Us page](https://keiko-corp.netlify.app/contact.html)
> > You can add this in the homepage though.
> 
> I am working on the homepage contact us section. Is it okay?
There are already issues raised by others for this
#158 
#82

**Comment by nemo0** [comment]
Check it here, [https://i.ibb.co/JR48YKY/Screenshot-2020-10-02-191909.png](url). I am working on this part.

**Comment by chetas411** [comment]
> 
> 
> Check it here, https://i.ibb.co/JR48YKY/Screenshot-2020-10-02-191909.png. I am working on this part.

ok then.

**Comment by brittneypostma** [comment]
Both of the pr's that are associated with this issue have conflicts present in them. Remember to run `git pull upstream master` before pushing your changes. @nemo0 and @chetas411 could you update the status of this issue?

**Comment by nemo0** [comment]
> Both of the pr's that are associated with this issue have conflicts present in them. Remember to run `git pull upstream master` before pushing your changes. @nemo0 and @chetas411 could you update the status of this issue?

I am done with the contact section. But each time I pull before pushing, I get issues. Resolving the issues results a broken site. Maybe I am doing something wrong. I'll try again.

**Comment by chetas411** [comment]
> 
> 
> > Both of the pr's that are associated with this issue have conflicts present in them. Remember to run `git pull upstream master` before pushing your changes. @nemo0 and @chetas411 could you update the status of this issue?
> 
> I am done with the contact section. But each time I pull before pushing, I get issues. Resolving the issues results a broken site. 
>
Try this it may help:
first add the original repo as a remote upstream in your local forked one:
`git remote add upstream [upstream.git]`
then,
`git checkout master `
`git fetch --all`
`git pull --rebase upstream master`
`git push origin master`

**Comment by brittneypostma** [comment]
Yes, try what chetas mentioned @nemo0 and please finish out this issue before creating new ones.

**Comment by brittneypostma** [comment]
Are one of you still working on this? Closing out the other issue.
![image](https://user-images.githubusercontent.com/45889730/94948761-da1b2f00-04ad-11eb-9faf-865135aeb6cb.png)

**Comment by chetas411** [comment]
Yeah , I guess @nemo0  is still working on it, if he faces some problem then I won't mind doing this one.

**Comment by nemo0** [comment]
Thanks @chetas411 for the tip. Are you working on the master branch itself? Or creating a new branch?

**Comment by chetas411** [comment]
@brittneypostma right now there are many issues related to visibility of many elements on the website and there are multiple contact us section and multiple css files have been changed , by the way you mentioned to come up with a new mock up for the site , I am waiting for it then would start the work for renovating the site .
