### ISSUE TITLE
[ CREATE ] - Header

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Keiko-Corp#2]
Create a header section similar to the image below: 
![image](https://user-images.githubusercontent.com/6190356/94613196-21ca6c80-029c-11eb-9bfe-70c99f615bd2.png)

#### IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING

**Comment by adithyakam** [comment]
HI Matt,

claimimng this

**Comment by UsmanKaramat** [comment]
Hi, I want to contribute on this project.
