### ISSUE TITLE
[FIX] Fixing Social Media Icons

### ISSUE THREAD

**Issue by dpcoolmufa** [zero-to-mastery/Keiko-Corp#219]
There are two rows of social media icons. Second row has extra space between the icons. I'm Working on it.

**Comment by aishaamir** [comment]
The icons are not visible in the dark mode. Can I work on it?

**Comment by dpcoolmufa** [comment]
I will See to it .

**Comment by dpcoolmufa** [comment]
The Footer sections Group1 and Group2 are not  visible  in light mode. You can work on that

**Comment by aishaamir** [comment]
ok
