### ISSUE TITLE
Adding Feature 2 and 3 according to Mock up

### ISSUE THREAD

**Issue by shray0027** [zero-to-mastery/Keiko-Corp#229]

**Comment by shray0027** [comment]
adding rest of features

**Comment by brittneypostma** [comment]
Feature 2 is already at issue #84

**Comment by brittneypostma** [comment]
Feel free to do feature 3

**Comment by shray0027** [comment]
ok

**Comment by brittneypostma** [comment]
@shray0027 I was mistaken, this is actually on another issue already. #6

**Comment by brittneypostma** [comment]
You can communicate with the person assigned that one, I'll close this one for now.

**Comment by shray0027** [comment]
@brittneypostma I have already made if the other one has not submitted I can send ??
