### ISSUE TITLE
[CREATE] - Feature Three

### ISSUE THREAD

**Issue by Rahulm2310** [zero-to-mastery/Keiko-Corp#244]
# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task
Create feature three, as shown below. Also add a cool SVG (free to use) and some lorem ipsum text.   

![ztmissue](https://user-images.githubusercontent.com/54268438/94954590-f4cdc200-0506-11eb-92b4-a0239e49b223.JPG)

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by Rahulm2310** [comment]
I am working on it and will create a PR asap.

**Comment by shray0027** [comment]
I have already created  feature 3

**Comment by brittneypostma** [comment]
The correct svg is project-three.svg in the images folder. Please replacing the current content and remove the old image if you are taking this on.

**Comment by brittneypostma** [comment]
@shray0027 even though it has been implemented doesn't mean it is aligning with the mockup.

**Comment by Rahulm2310** [comment]
> I have already created feature 3

**Comment by shray0027** [comment]
@Rahulm2310 you can see comments above  Issue was created 2hrs ago , I have already completed it.

**Comment by Rahulm2310** [comment]
@shray0027 It is already assigned to me brother

**Comment by shray0027** [comment]
You can see issue 24 in closed section , I have sent pull request to her ,you can do other task

**Comment by Rahulm2310** [comment]
@shray0027 I think we should not discuss more on this.... @brittneypostma knows more abt it.

**Comment by shray0027** [comment]
thats so unfair I have coded already I created the same issue and was closed , you can show some generousity bby not doing which is already done

**Comment by brittneypostma** [comment]
@shray0027 I don't understand the hostility, you still get credit for the pr you did. It was not styled according to the mockup, so it was able to be edited. Lots of things are going to change and be edited before the site is complete. This is not a final design as soon as a pr is merged and is constantly moving and changing.

**Comment by Rahulm2310** [comment]
@brittneypostma The feature design is breaking for small screens.
![error1](https://user-images.githubusercontent.com/54268438/94960329-55adc800-0510-11eb-8e78-fc2ad1494866.JPG)
![error2](https://user-images.githubusercontent.com/54268438/94960336-58a8b880-0510-11eb-89e7-bd993cdb97f3.JPG)
Should I create an issue and work on it ?

**Comment by brittneypostma** [comment]
There is an issue for responsiveness/media query already #32 give it a couple of days.
