### ISSUE TITLE
[ CREATE ] - Blog Page

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Keiko-Corp#25]
Create a blog page with similar design to: 
Dont worry about the Navbar, Hero Image or Email bar, we can use these from the other tasks.
![image](https://user-images.githubusercontent.com/6190356/94810699-459cc800-03ec-11eb-9bba-6a6df7a1122a.png)

#### This task was created for jomefavourite (Discord Username)

**Comment by TonyOuma** [comment]
Hello, can I pick this up. And would like to know which CSS framework is preferred?

**Comment by MattCSmith** [comment]
@TonyOuma This task was created for Jomefavourite over on Discord. 

Feel free to create an issue/task for either:
- Recruitment/Job posting section
- Previous work/portfolio section. 

In order to keep the project friendly for developers of all levels, we are rolling with Vanilla.

**Comment by jomefavourite** [comment]
I'm taking the task

**Comment by jomefavourite** [comment]
Thanks @MattCSmith
