### ISSUE TITLE
[CREATE] CONTACT US HTML form  like mockup

### ISSUE THREAD

**Issue by shray0027** [zero-to-mastery/Keiko-Corp#261]
# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

 > this task is creation of HTML form as shown in mockup

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by batistaDev1113** [comment]
Hi @shray0027 ,

I would like to work on this issue if possible.  By the way, where can I find the mockup?

Thank you in advance

**Comment by shray0027** [comment]
@batistaDev1113 Yes , I had cretead the page in index.html only ,I have already done that just waiting to get assignee.I have not included background image you can include it
