### ISSUE TITLE
Fixing Feature section

### ISSUE THREAD

**Issue by Surya742** [zero-to-mastery/Keiko-Corp#272]
# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

Features section is not properly aligned. I will work on it so that it looks beautifully aligned and maintain the page flow.

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by Surya742** [comment]
@aneagoie @MattCSmith kindly verify and merge my PR.

**Comment by brittneypostma** [comment]
@Surya742 I'm not sure the styling provided is the desired effect. There is overlapping and a horizontal scroll. 
![image](https://user-images.githubusercontent.com/45889730/94992531-8c0f3580-0558-11eb-9879-dacfcfb82963.png)

**Comment by merirosewins** [comment]
- name: google-api-fetch-token-action
  uses: cardinalby/google-api-fetch-token-action@1.0.0


HELP please tell me what my "yml file" is and how I enter tokens in it and like what the code above is for that I have from somewhere since I forgot please help I'm new to this stuff :) -Meri Rose Winsor 😃💯

**Comment by Surya742** [comment]
![Keiko Corp - Google Chrome 10_4_2020 1_47_30 AM](https://user-images.githubusercontent.com/60179206/95001099-5e6fce00-05e4-11eb-9356-3fcfa6b95c6c.png)
@brittneypostma  When I had made this PR this was looking great, but maybe due to some merging from other contributors some code might changed on which my code creating this issue, I can made it again like that if you assign me.

**Comment by brittneypostma** [comment]
That is a possibility, but the conflicts still need to be fixed as the pr sent through makes the layout worse.
