### ISSUE TITLE
[UPDATE] index.html and contact.html HEADER links to include features.html, testimonial.html and team.html  

### ISSUE THREAD

**Issue by Guitarhub786** [zero-to-mastery/Keiko-Corp#273]
# New Task:

I have already added HEADER for contact.html and home link for contact.html
I will do the same for the following links. Where the links will work once created, but the CSS of the already created index.html and contact.html looks will be consistent.

      <li>Features</li>
      <li>Testimonial</li>
      <li>Team</li>

To link to;

features.html
testimonial.html
team.html

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

<Detail the problem/task>

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [ x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [ ] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by Guitarhub786** [comment]
Waiting for the following PR task to be approved, as they are linked to the same solution.

[ADD] Header to contact page #268
https://github.com/zero-to-mastery/Keiko-Corp/issues/268

**Comment by brittneypostma** [comment]
I just merged in the pr and am going to close it, but this is what I meant by the issue.

![image](https://user-images.githubusercontent.com/45889730/94974287-0f3e7600-04dc-11eb-83c7-5bc6fc9e7192.png)
