### ISSUE TITLE
Adding Transition Animation

### ISSUE THREAD

**Issue by aman339** [zero-to-mastery/Keiko-Corp#283]
# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

Add some cool transition animation

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x ] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x ] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by geeks5551** [comment]
hey, can I contribute to the adding transition animation as well as translation and other advanced transition and CSS  effects? looking really interesting ? Can you assign me this issue
