### ISSUE TITLE
settings page for the blog

### ISSUE THREAD

**Issue by aditijhaa9901** [zero-to-mastery/Keiko-Corp#29]
making a settings page for a blog app that will contain options to edit all basic info about a user like password, user_id, description and other things.

**Comment by aditijhaa9901** [comment]
i want work on this issue. Please assign me this issue.

**Comment by MattCSmith** [comment]
@aditijhaa9901 The idea behind this project is to remain simple and beginner friendly. As such I am hesitant to add complexities such as databases/authentication and frameworks. 

If you wish to make novelty behaviour mimicking the log in behaviour with vanilla JS then feel free to go ahead with this. But lets avoid over complicating a simple project. 
There are a couple of more advanced projects in the ZTM space that might benefit from more advanced features. I can point you in the direction of these if you are interested.

**Comment by brittneypostma** [comment]
Since there has been no pr and it was discussed that this may be too complicated, i am closing for now.
