### ISSUE TITLE
[FIX]Fix Footer Font Colors in Dark Mode

### ISSUE THREAD

**Issue by leonyangela** [zero-to-mastery/Keiko-Corp#290]
![1601703852813](https://user-images.githubusercontent.com/38250310/94984451-3fd2ee00-0576-11eb-9308-c4ba803a908e.jpg)

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

I want to fix the footer font colors in Dark Mode, Thank you

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by brittneypostma** [comment]
I am still showing the footer colors as dark in your deploy preview. The javascript in the code has a debug log, maybe it is not being applied correctly?

![image](https://user-images.githubusercontent.com/45889730/94992589-0d66c800-0559-11eb-8318-4685a7db5d25.png)

**Comment by leonyangela** [comment]
Hey britney, it's working on my localhost. I would like to know is it working or is it still has a problem?
![image](https://user-images.githubusercontent.com/38250310/94993059-7cbfd480-05b8-11eb-8825-eccca2ebcad9.png)
