### ISSUE TITLE
[ CREATE ] - Companies Banner

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Keiko-Corp#3]
Create a bar similar to the one pictured below. Use a handful of your favourite tech companies. 

![image](https://user-images.githubusercontent.com/6190356/94613420-78d04180-029c-11eb-9436-51f2997eb8a4.png)

### IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING

**Comment by christine-aqui** [comment]
Claiming Companies Banner 🚀

**Comment by Udaygajavalli** [comment]
@christine-aqui Are you still working on it?

**Comment by christine-aqui** [comment]
> @christine-aqui Are you still working on it?

Yea, will pr later today.

**Comment by brittneypostma** [comment]
Closing as complete.
