### ISSUE TITLE
[ CREATE ] - Jobs Listing Page

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Keiko-Corp#31]
Bruno wants to be able to list the Keiko's job positions. He doesnt really have an idea on how he wants this to look, so has requested you pull inspiration from examples around the web to come up with something awesome. 
The only requirements he has are: 
- The page must be designed to accommodate many listings
- Must display `Job Title`, `Short Description`, `Salary`, `Start Date`, `Full Time/Part Time`. If you can think of more feel free to add them. 
- Must be a separate page

If the Navbar/footer are available from the index page, feel free to incorperate them, other wise just add a simple place holder and we can create a ticket to add these later. 

#### PLEASE CLAIM THE TASK BY COMMENTING BELOW. FIRST COME FIRST SERVE

**Comment by batistaDev1113** [comment]
Hi @MattCSmith ,

I would like to work on this one if possible.
Thank you

**Comment by batistaDev1113** [comment]
Thank you @MattCSmith !  I will begin to work on it!
