### ISSUE TITLE
[CREATE[ - media queries for responsiveness 

### ISSUE THREAD

**Issue by comebackid87** [zero-to-mastery/Keiko-Corp#32]
I can work on adding media queries for the site to be viewed on mobile phones, tablets and laptops.

**Comment by JatinAgrawal94** [comment]
I can work on adding media queries to the site , can you assign this task to me?

**Comment by atharv123-wq** [comment]
Would like to work on media queries

**Comment by comebackid87** [comment]
Working on media queries already
