### ISSUE TITLE
Shopping List using a HTML

### ISSUE THREAD

**Issue by Bihari420** [zero-to-mastery/Keiko-Corp#325]
# New Task:
Shopping List using a HTML
[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task
Shopping List using a HTML
<Detail the problem/task>

### Who is the task for?
me(private task)
[//]: # 'Place and x in between the brackets to check'

- [x

 ] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [ ] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by brittneypostma** [comment]
This is not something in the mockup and with no pr attached for now I am closing this.
