### ISSUE TITLE
Fix Accessibility Issue in Contact Form

### ISSUE THREAD

**Issue by adityasingh2509** [zero-to-mastery/Keiko-Corp#330]
# New Task: Fix Accessibility Issue in Contact Form

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

Add 'aria-labelledby' to input elements to enhance Accessibility!

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by brittneypostma** [comment]
This is a great idea. However, there are 6 files changed in this pr and I am unable to sift through what is going on with the files. Make sure to run `git pull upstream master` to get the latest changes and only change files associated with your issue.

**Comment by brittneypostma** [comment]
Sorry, accidentally closed the issue instead of the pr. I have closed the pr now, but left the issue open. After pulling the latest updates from the master branch, this can be resubmitted.

**Comment by adityasingh2509** [comment]
I did the 'pull upstream master' before pushing the solution but got an overwritten version of the branch. My previous merged PR has been overwritten as well. Somewhere there has been an improper push or merge.

**Comment by brittneypostma** [comment]
Okay, sorry about that. We had an issue with the site and had to revert some changes. I am cleaning up old issues and will address accessibility when I create the new ones for tomorrow.

**Comment by adityasingh2509** [comment]
No problem. Thank you!
