### ISSUE TITLE
No new issues until tomorrow! 

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#333]
Clean up time, no new issues for now. I am working on a new mockup that I should have ready by tonight. Please work on any issues assigned to you and make sure your pr is linked to the issue so that we can check them. I have went through and merged or commented on all linked issues to pr's. Any others not finished will be closed tomorrow. Any new issues created after this will be closed until old issues are cleaned up.

**Comment by khushali77** [comment]
Hi! Can I align the text of features, testimonials and never miss any updates? It looks unordered!
