### ISSUE TITLE
social media buttons

### ISSUE THREAD

**Issue by WayneMacMavis** [zero-to-mastery/Keiko-Corp#336]
# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### social media buttons

<misalignment with social media expanding buttons. Doesn't look good>

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by geeks5551** [comment]
hey, can I add required social media buttons using required advanced CSS, transition, and translation? looking really interesting? can you please assign me with this issue ?

**Comment by brittneypostma** [comment]
No new issues are to be added at this time, check issue #333. All problems with the site will be addressed later today. We are working to clean up current problems.
