### ISSUE TITLE
Enhancement of the website like mockup

### ISSUE THREAD

**Issue by khushali77** [zero-to-mastery/Keiko-Corp#339]
# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task?

Earlier the Testimonials heading was floating on left side which is to be aligned at the center.
Also, the "Never miss an update" was repeating twice, out of which only one should be present.
Even the Submit button was green which is to be blue and font color should be white.

### Who is the task for?

This task is for me.

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by brittneypostma** [comment]
These issues will be addressed after older ones are cleaned up. There is an [Everyone] issue that says no new issues until tomorrow. I will be creating a new figma mockup and new issues tonight.
