### ISSUE TITLE
Correct the styling of Footer section

### ISSUE THREAD

**Issue by kunalprakash1309** [zero-to-mastery/Keiko-Corp#342]
# New Task: I would like to work on footer section

[//]: # 'I would like to work on footer section'

#### What is the task 

<Currently the styling of footer is not up to the mark. So correcting the footer section is task>

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by brittneypostma** [comment]
No new issues at this time, please see issue #333
