### ISSUE TITLE
Header Styling

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#360]
- Create consistent header styling across the site similar to the image below. (Each page can be sent as its own pull request) 
- Use color variables to align with mockup design.
- Fix positioning of elements.
- Make header stretch to the maxWidth variable.
![image](https://user-images.githubusercontent.com/45889730/95009250-819f7b00-05ee-11eb-8b78-aca571c8c584.png)

**Comment by aishaamir** [comment]
I will do it

**Comment by brittneypostma** [comment]
There are multiple tasks for this issue. @aishaamir could  you clarify what you want to work on. Others have asked about working on parts of this.

**Comment by nemo0** [comment]
Hi @aishaamir ! Are you still working on it?

**Comment by aishaamir** [comment]
Hi @nemo0. Yes. I will inform you if i am not able to do it

**Comment by aishaamir** [comment]
> There are multiple tasks for this issue. @aishaamir could you clarify what you want to work on. Others have asked about working on parts of this.

Fixing the navbar so it looks like the mock-up..

**Comment by nemo0** [comment]
Okay! Thanks. 😀

**Comment by batistaDev1113** [comment]
@brittneypostma an I specifically work on the home page regarding this issue?

Thank you

**Comment by batistaDev1113** [comment]
never mind...I can see somebody else is working on it!

Thanks

**Comment by brittneypostma** [comment]
@batistaDev1113 if you want to work on the overall style of the header, but avoid the links since they are in another issue, you may take this one over. Others have been given time to create a pr and it is not complete.

**Comment by batistaDev1113** [comment]
@brittneypostma I can definitely do that.  Starting work on it right now!

Thank you

**Comment by brittneypostma** [comment]
Lots of things going with the Header at the moment, make  sure you are pulling from the upstream master before committing changes.

**Comment by batistaDev1113** [comment]
@brittneypostma I just executed te PR but there seems to be a conflict present.  It seems there has been another PR for the same.  Please see below a screenshot of my final result:
![header-style](https://user-images.githubusercontent.com/15971206/95120745-ffad7000-071b-11eb-8f19-be4e8ce58171.png)

Could you take a look at this?  I had pulled from upstream before doing any work just an FYI

**Comment by brittneypostma** [comment]
@batistaDev1113 make sure you link the issue in the pr next time, it allows the issue to close automatically.

**Comment by batistaDev1113** [comment]
@brittneypostma I am confused.  The issue number was added to the PR.

I have attached a screenshot of my PR.  If you go back and you hover the issue #, it recognizes the issue that is being fixed.

![issue](https://user-images.githubusercontent.com/15971206/95128424-65532980-0727-11eb-8f27-708ce4d303c7.png)

For some reason it was placed above the image instead of below to where it says "Fixes #" but it is there.

Please let me know of that is correct, to avoid the mistake again

**Comment by brittneypostma** [comment]
My bad I missed that,  not sure why it didn't auto close it though.

**Comment by batistaDev1113** [comment]
@brittneypostma No worries....I am glad to hear I did it correctly.  Whatever I can do to not overload you guys with work and make the process smoother.  Not sure why it did not close automatically though!
