### ISSUE TITLE
Hero Styling

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#361]
- Make the hero section look more like the image below.
- Use font-size and color variables provided in global.css
- Make the image stack on top at sm breakpoint as in 2nd image below.

![image](https://user-images.githubusercontent.com/45889730/95009358-7436c080-05ef-11eb-9351-1b1750cd2b33.png)
![image](https://user-images.githubusercontent.com/45889730/95009386-b5c76b80-05ef-11eb-9f2f-15c688124ab2.png)

**Comment by qwerty-rgb** [comment]
i can do it please assign me the task

**Comment by qwerty-rgb** [comment]
I have corrected it but unable to push even after reading your terms in the readme section please help

**Comment by brittneypostma** [comment]
@qwerty-rgb maybe you can show what's going on in the discord channel keiko-corp. Not sure how to really help you without more info. I will assign you this task for 24 hours, then open it back up.

**Comment by NavjotBansal** [comment]
Hey @brittneypostma  I am ready with changes feel free to mention me in the comment will raise the Pull Request for the same

**Comment by KryptonBD** [comment]
If s/he unable to complete the task, assign it to me. @brittneypostma

**Comment by KomalPandey15** [comment]
I can do this task

**Comment by brittneypostma** [comment]
@KryptonBD you may try this now as well.
