### ISSUE TITLE
Company Section

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#365]
- Change background color to use new color variable purple
- add title and paragraph text

![image](https://user-images.githubusercontent.com/45889730/95009535-d3e19b80-05f0-11eb-8ce5-5222b9b8b2c4.png)

**Comment by krish7777** [comment]
@brittneypostma Can I work on this?

**Comment by krish7777** [comment]
Should the color of the texts be changed because there is a default text variable already in the global CSS file?

**Comment by brittneypostma** [comment]
Yes,  everything going forward should use the provided variables for consistency.

**Comment by krish7777** [comment]
![company-section](https://user-images.githubusercontent.com/52481369/95010839-2dc27f80-064a-11eb-9e25-10f228f4c7bb.png)

Is this design fine? The default text color is grayish instead of white

**Comment by NavjotBansal** [comment]
Wokring on it!

**Comment by brittneypostma** [comment]
@krish7777 you are assigned this task, you have 24 hours to complete it or I will pull @NavjotBansal's pr

**Comment by NavjotBansal** [comment]
@brittneypostma correct me if i am wrong but @krish7777 commit looks exact as mine. please consider this case of plagiarism

**Comment by NavjotBansal** [comment]
@brittneypostma as @krish7777 was initially having problems fixing the issue i took the opportunity , no issues as he was the first to claim it ✌️

**Comment by brittneypostma** [comment]
I noticed both of you used white as the color for the text and the logos. It should be the lightBlue provided in the global.css color variables. I am reopening and will pull the first one that completes it. @NavjotBansal @krish7777

**Comment by krish7777** [comment]
@brittneypostma I would like to give this opportunity to @NavjotBansal because he had worked on the previous PR and was not able to merge it

**Comment by brittneypostma** [comment]
@NavjotBansal he passed this last part to you. I just updated the svgs on my end. The only thing left to fix is the color of the text in the company section. It needs to use the lightBlue variable. Can you complete this?

**Comment by NavjotBansal** [comment]
Yeah i can do that @brittneypostma but the design mockup has different color with respect to what you are saying can you please confirm once i will do and create a PR
