### ISSUE TITLE
Testimonials Heading

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#366]
- Fix styling on the testimonials header.
- Give the entire section the lightBlue variable background color.

![image](https://user-images.githubusercontent.com/45889730/95009651-aea15d00-05f1-11eb-8c8a-d9d7c21ffa57.png)

**Comment by pritesh11-10** [comment]
I would like to claim this issue. Thanks..

**Comment by khushali77** [comment]
Can I work on this issue?

**Comment by brittneypostma** [comment]
@pritesh11-10 please only claim one issue at a time. I'm assigning to @khushali77

**Comment by brittneypostma** [comment]
Text looks better, not sure on the sizing and spacing, but color is definitely no like the mockup. I'll pull the first one that fixes it.
