### ISSUE TITLE
[Create]Carousel without Bootstrap for Testimonials

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#367]
- Use the quote-box.svg to create a carousel similar to the one below.
- Use color variables provided in global.css
- Do not use bootstrap or jQuery.

![image](https://user-images.githubusercontent.com/45889730/95009689-06d85f00-05f2-11eb-97ee-bd0e6231516a.png)

**Comment by Manoj13-coder** [comment]
assign it to me

**Comment by vanya-24** [comment]
I would like to work on this! Please assign this to me! @brittneypostma

**Comment by Manoj13-coder** [comment]
i am working on it

**Comment by brittneypostma** [comment]
This has still not been implemented as shown. @vanya-24 if you want to give it a shot. I will merge in the first person to add it in correctly.
