### ISSUE TITLE
Footer Styling

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#368]
- Update colors using CSS variables provided in global.css
- Make sure the columns stack at the sm breakpoint.

![image](https://user-images.githubusercontent.com/45889730/95009819-e230b700-05f2-11eb-9af8-1f51a0ef2056.png)
![image](https://user-images.githubusercontent.com/45889730/95009846-fd032b80-05f2-11eb-90e2-77aff5007f19.png)

**Comment by omriattiya** [comment]
Hi, I would like to do it 👍

**Comment by advaith-unnikrishnan** [comment]
Hi, I would like to work on this
