### ISSUE TITLE
[Create]Contact Page Form

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#371]
- Add in a form to contact.html similar to the one below.
- Use the red color variable from global.css instead of the blue button.

![image](https://user-images.githubusercontent.com/45889730/95009929-8f0b3400-05f3-11eb-960e-184a67a33003.png)

**Comment by pritesh11-10** [comment]
I would like to work on this. Hope I get this assigned. Thanks

**Comment by advaith-unnikrishnan** [comment]
I would like to work on this issue.

**Comment by Abhishekchauhan089** [comment]
@brittneypostma I would like to work on this project

**Comment by kratikasinghal** [comment]
Hey!! @brittneypostma I would like to work on this issue

**Comment by khushali77** [comment]
Can I work on this issue?

**Comment by sb19** [comment]
i have added the red color variable from global.css instead of the blue in contact.css.
#408

**Comment by brittneypostma** [comment]
@sb19 @pritesh11-10 was the first to comment, they are given 24 hours to complete the task.

**Comment by vanya-24** [comment]
I would like to work on this . Please assign me! @brittneypostma
