### ISSUE TITLE
Assessibility

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#374]
- Check color contrast for AA compliance
- Check dark mode as well.
- Add aria-labels and roles as needed.

**Comment by leonyangela** [comment]
Can I try to do it?

**Comment by comebackid87** [comment]
Please can i work on this issue.i will make my pull rewuest today.

**Comment by brittneypostma** [comment]
@comebackid87 I haven't seen a pr on this. How far along are you?

**Comment by maenad** [comment]
Hello! Since this was abandoned, can I take it?

**Comment by christinaworkman** [comment]
I can work on more of the a11y issues here.
