### ISSUE TITLE
[NEW TASK} Add login and signup pages to the site

### ISSUE THREAD

**Issue by comebackid87** [zero-to-mastery/Keiko-Corp#392]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

The site currently has no admin panel where users can login and register. I can create the login and signup pages using HTML and CSS. 

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [X] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [X] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by akshatz** [comment]
I would like to claim it

**Comment by brittneypostma** [comment]
There actually is already a login.html page created.  It did need to be styled using the site colors.

**Comment by akshatz** [comment]
Ok

**Comment by comebackid87** [comment]
@brittneypostma i will style the already existing login page and add signup page as well. Please assign me to the task.

**Comment by brittneypostma** [comment]
Sounds good, I'll leave the issue here and assign it to you.
