### ISSUE TITLE
Broken link in Readme File

### ISSUE THREAD

**Issue by AmrutaKoshe** [zero-to-mastery/Keiko-Corp#396]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

Update the mockup design link in the readme file. Currently, when you click the link it gives 404 not found error.

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [ ] I created this task for me to complete, I will create a PR soon.
- [x] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by NavjotBansal** [comment]
working on it

**Comment by sravya-challa-au3** [comment]
can i try this ?

**Comment by brittneypostma** [comment]
@sravya-challa-au3 sure they created it for someone else to claim it says. Here is the updated link to the figma file.

https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10

**Comment by comebackid87** [comment]
@brittneypostma demo folder is not available in repository. Please advise link where to collect it.

**Comment by christine-aqui** [comment]
@sravya-challa-au3 Still working on this?

**Comment by brittneypostma** [comment]
> @sravya-challa-au3 Still working on this?

You can take it,  I posted the link to the figma file above.

**Comment by sravya-challa-au3** [comment]
sorry, no 
@christine-aqui you go ahead

**Comment by christine-aqui** [comment]
@brittneypostma @sravya-challa-au3 
ok, thanks.
