### ISSUE TITLE
[ CREATE ] Feature One

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Keiko-Corp#4]
Create feature one, as shown below. use a suitable image from Unsplash or similar (ensure its free to use)
add some interesting text or use a generator such as [ Pirate Ispum ](https://pirateipsum.me/) or [ Cupcake Ispum ](http://www.cupcakeipsum.com/)

![image](https://user-images.githubusercontent.com/6190356/94622280-d3bc6580-02a9-11eb-98f9-fc93197fb010.png)

#### IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING

**Comment by dontech09** [comment]
I like to work on that

**Comment by crenspact02** [comment]
I want to work on this!

**Comment by Udaygajavalli** [comment]
@crenspact02 Hey, I already made PR for this.
