### ISSUE TITLE
Fix the input field for the email address

### ISSUE THREAD

**Issue by sanjithpk** [zero-to-mastery/Keiko-Corp#405]
# New Task:

#### What is the task

Fix the input field for the email address is not being displayed in the Never miss an update section

### Who is the task for?

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by marzukiberg** [comment]
@sanjithpk 
If you dont mind i will fix this one sir

**Comment by brittneypostma** [comment]
@marzukiberg sanjithpk claimed this first and it is assigned
