### ISSUE TITLE
Fixing the navbar hover effect to avoid disappearing of buttons

### ISSUE THREAD

**Issue by taniyahinduja** [zero-to-mastery/Keiko-Corp#409]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

<Detail the problem/task>

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by brittneypostma** [comment]
Please edit with what the task details.

![image](https://user-images.githubusercontent.com/45889730/95016780-2cca2780-0623-11eb-925b-3e7d6121bb9b.png)

Also, this overlaps a bit with issue #360, make sure you have the most updated copy by running `git pull upstream master` and you are following the new mockup.

**Comment by brittneypostma** [comment]
I'm actually going to close this issue as to not create confusion. Please reference issue #360 and communicate there to assign individual tasks.
