### ISSUE TITLE
[Create]Links to all pages created

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#411]
- Create a menu in the current nav menu that drops down when hovered over.
- Include a link to any page not already linked in the dropdown. (login, job-listing, about, and blog.html)

**Comment by nemo0** [comment]
I am taking it.

**Comment by nemo0** [comment]
Wasn't this assigned to me?

**Comment by brittneypostma** [comment]
@nemo0 yes, I am not merging it in. If you have a pr within 24 hours, I pull merge yours instead.

**Comment by nemo0** [comment]
But the current menu has some style issues! Whenever I add child elements to a li, the other li's are getting invisible! So, I was thinking to work on it after the menu like the mockup gets pulled. Is it possible? I am also attaching an image of the problem.
![image](https://i.ibb.co/cJdtLTm/Screenshot-2020-10-05-200806.png)

**Comment by brittneypostma** [comment]
@nemo0 the current styling buttons need to be removed per the mockup. The list of links I'm talking about would be something like this:
![image](https://user-images.githubusercontent.com/45889730/95110692-6cb90980-070c-11eb-9618-b15ffdc573be.png)
I will give you until the end of the day, then I'll allow others to work on it.

**Comment by batistaDev1113** [comment]
@brittneypostma , If @nemo0 can't make it I will take over

**Comment by dpcoolmufa** [comment]
Please link pages or sections in the footer section also.

**Comment by batistaDev1113** [comment]
@brittneypostma Thank you!  I am on it :-)
