### ISSUE TITLE
Changing the layout of features

### ISSUE THREAD

**Issue by AmrutaKoshe** [zero-to-mastery/Keiko-Corp#415]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

In the features section, place the image and text side by side as given in the mock design. Also make the text size smaller like the rest of the page.

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by brittneypostma** [comment]
Remember to think about the responsiveness too and make it stack on smaller screens.

**Comment by AmrutaKoshe** [comment]
> Remember to think about the responsiveness too and make it stack on smaller screens.

Okay Thanks! I would need to add a new css file, right?
