### ISSUE TITLE
[Edit]Styling of dark mode toggle

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#419]
- Edit styling of toggle button to look like mockup

**Comment by comebackid87** [comment]
I would like to take on this challenge. Please assign me.

**Comment by paudiaz122** [comment]
Is it done?

**Comment by darrylsepeda** [comment]
I solved this issue (before realise it was assigned to @comebackid87) while fixing the menubar's width on large breakpoint.
please assign it to me if there is no update on this issue?

<img width="1919" alt="Screenshot 2020-10-05 at 14 31 37" src="https://user-images.githubusercontent.com/5493333/95052987-fcb18000-0719-11eb-8138-647ca75fd4f6.png">

**Comment by comebackid87** [comment]
Still working on it @brittneypostma will make my pr soon
