### ISSUE TITLE
[Fix]Dark Mode Broken

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#434]
Something happened to dark mode and it is not working. Need someone to check it out and fix it. This is a separate issue from styling Dark Mode.

**Comment by batistaDev1113** [comment]
@brittneypostma I would like to work on this!

**Comment by brittneypostma** [comment]
@batistaDev1113 just saw someone already fixed it in a pr right after i created the issue.

**Comment by batistaDev1113** [comment]
Np!  Thank you for the heads up!
