### ISSUE TITLE
[Fix]Subscribe section sticks when switching from dark back to light mode

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#441]
- Fix colors for subscribe section, so they switch back when light/dark mode is toggled

![image](https://user-images.githubusercontent.com/45889730/95022767-3f565800-0647-11eb-990e-d2747f8ad2d3.png)

**Comment by Navdeepsingh4298** [comment]
may i do this ?

**Comment by Navdeepsingh4298** [comment]
that's what i notice at first time after toggle dark mode.

**Comment by rickymaggio02** [comment]
need any help?

**Comment by Navdeepsingh4298** [comment]
> need any help?

sure,

**Comment by Navdeepsingh4298** [comment]
issue fixed.

**Comment by Navdeepsingh4298** [comment]
error while pushing changes

**Comment by Navdeepsingh4298** [comment]
fixed issue #441

**Comment by Navdeepsingh4298** [comment]
"git push upstream subscribefix
remote: Permission to zero-to-mastery/Keiko-Corp.git denied to Navdeepsingh4298.
fatal: unable to access 'https://github.com/zero-to-mastery/Keiko-Corp.git/': The requested URL returned error: 403"

i'm facing above error can anyone help me please.
