### ISSUE TITLE
Footer style similar to the Figma model

### ISSUE THREAD

**Issue by rickymaggio02** [zero-to-mastery/Keiko-Corp#452]
# Footer

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

creating  a footer with the color style as the figma model.

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x ] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x ] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by brittneypostma** [comment]
Yes, please change that header color to the correct one and if you can check dark mode coloring too.

**Comment by rickymaggio02** [comment]
I modified the js file for the dark mode (the footerrow call was missing for the light mode) and i changed some of the style of the components
