### ISSUE TITLE
[Fix]Responsive Feature Section

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#453]
The current Feature section layout breaks as soon as it hits the breakpoint and margins are off.
- Use css grid for base layout
- Use flex at the min-width breakpoint.
- Change margins/padding to use the variables provided in global.css

**Comment by changangus** [comment]
Hi Brittney, could I get assigned this issue?

**Comment by KomalPandey15** [comment]
Hey Brittney, I would like to solve this bug

**Comment by icoderharshit** [comment]
Hey Brittney ! Can I contribute a bit in this ? and I am a Graphics Designer, if you would like to see my work...I might help you out in improving the overall design of the website(colors, themes, layout) :)

**Comment by icoderharshit** [comment]
@brittneypostma

**Comment by brittneypostma** [comment]
This is fixed.
