### ISSUE TITLE
Company Section Responsive

### ISSUE THREAD

**Issue by jomefavourite** [zero-to-mastery/Keiko-Corp#478]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

I'll like to make the images / svg at the company section responsive so that it will look good on mobile.

<Detail the problem/task>

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by brittneypostma** [comment]
This is the current mobile smallest size.
![image](https://user-images.githubusercontent.com/45889730/95094131-8c920280-06f7-11eb-98c2-043dcabed5c4.png)

This is what it should look like. They should have a min-width and the margin/padding should get smaller.
![image](https://user-images.githubusercontent.com/45889730/95094187-a0d5ff80-06f7-11eb-80de-cf006e03f791.png)

**Comment by jomefavourite** [comment]
On it

**Comment by jomefavourite** [comment]
Please could the repo be labelled `Hacktoberfest`

**Comment by brittneypostma** [comment]
@jomefavourite the styles you created look great, but they need to be integrated into the index.html, not on their own page.

**Comment by jomefavourite** [comment]
Okay I wasn't sure if it were to be integrated or not. So I'll have to make a new PR  or could I make changes from this PR?

**Comment by jomefavourite** [comment]
@brittneypostma It's done now
