### ISSUE TITLE
Heading in Hero: Color Bug (on turning Dark Mode off)

### ISSUE THREAD

**Issue by icoderharshit** [zero-to-mastery/Keiko-Corp#479]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

"THE BEST TECH STARTUP" heading in the hero section of the website, doesn't switch back to black/greyish color on dark mode toggle.
 
### Who is the task for?
Please assign me this issue, so that I start working over it and create a PR soon :) Looking forward to your reply @brittneypostma 
[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by icoderharshit** [comment]
Please add the label "hacktoberfest" or just check if this is good to go, because I needed to mark this contribution for Hacktoberfest. Looking forward to @brittneypostma for reply, and hoping to get the PR merged successfully :)
Regards.

**Comment by icoderharshit** [comment]
Please check the PR @brittneypostma , I resolved the conflicts and mentioned the changes with multiple single comments on GitHub, if still not able to merge..Let me know, I'll create a new PR with the same changes and fix the issue :)

**Comment by brittneypostma** [comment]
Dark mode is getting an entire overhaul in #489
