### ISSUE TITLE
[Create]Meet the Team needs its own html file

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#486]
- Create meet-the-team.html
- Move Meet the Team section (commented out in index.html) to the new page.
- Update styling links.

**Comment by Navdeepsingh4298** [comment]
i will do that

**Comment by Navdeepsingh4298** [comment]
can you show me the mockup for that?

**Comment by heftymouse** [comment]
Hi, can I do this for Hacktoberfest?

**Comment by khushali77** [comment]
Can I work on this?

**Comment by brittneypostma** [comment]
There is no mockup for it @Navdeepsingh4298, but using the color variables in global.css and a similar style would work. If you already have a project you are working on, please let @heftymouse complete it. We want everyone to get a change to get in their pr's.

**Comment by KomalPandey15** [comment]
I can do this

**Comment by heftymouse** [comment]
Thanks a lot!

**Comment by heftymouse** [comment]
@brittneypostma @Navdeepsingh4298 was already assigned to another issue, should he still work on this?

**Comment by Navdeepsingh4298** [comment]
This issue is resolved. You may close this now
