### ISSUE TITLE
[Fix]Dark Mode needs an overhaul - [LARGE PROJECT]

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#489]
Dark mode is not following the current color scheme and breaks on half the sections. I would like a complete overhaul of dark mode. This will require a lot of work. Either the colors need to be updated everywhere to follow the global.css variable and use those. Or lots of lines of JavaScript need to be added/edited. I'll accept either implementation, but prefer CSS as it's easier to modify and change later.

**Comment by RedSquirrrel** [comment]
Hi Brittney,
 Unfortunately, I don't have to much experience in this area but I can give it a  try to resolve this. 
What colors do you want to use for dark mode?

**Comment by brittneypostma** [comment]
This doesn't look the best, but I threw it together. Just something using the color variables from global.css.

![image](https://user-images.githubusercontent.com/45889730/95114643-41d1b400-0712-11eb-885e-adc84fea1763.png)

**Comment by brittneypostma** [comment]
Here's the figma link. https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A8

**Comment by RedSquirrrel** [comment]
Alright, thank you :)

**Comment by brittneypostma** [comment]
@RedSquirrrel there have been changes, make sure you run a `git pull upstream master` to get the latest version.
