### ISSUE TITLE
Making some UI enhancements.

### ISSUE THREAD

**Issue by varunpusarla** [zero-to-mastery/Keiko-Corp#495]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # Making some UI enhancements to the site

#### What is the task

- The submit button can be made to change its color when hovered.
- Making the social media buttons appear in bold instead of italics when hovered over.

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x ] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [ x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by varunpusarla** [comment]
I'm working on this issue and will make a PR soon.

**Comment by brittneypostma** [comment]
I'm unsure what you mean by UI enhancements. Please make a new issue with a specific item so we do not create conflicts.
