### ISSUE TITLE
[FIX]Upgrading UI  in neverMissUpdate class index.html

### ISSUE THREAD

**Issue by BhuvaneshPatil** [zero-to-mastery/Keiko-Corp#496]
## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task
Enhancing the submit button in neverMissUpdate class
<Detail the problem/task>
setting its width to look good and adding hover effect to make it more beautiful.
### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x ] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [ ] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by brittneypostma** [comment]
Someone is working on a similar issue #470
