### ISSUE TITLE
[ CREATE ] - Feature Two

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Keiko-Corp#5]
Create feature two, as shown below. use a suitable image from Unsplash or similar (ensure its free to use)
add some interesting text or use a generator such as [ Pirate Ispum ](https://pirateipsum.me/) or [ Cupcake Ispum ](http://www.cupcakeipsum.com/)

![image](https://user-images.githubusercontent.com/6190356/94622388-02d2d700-02aa-11eb-8a70-fda6b10158a6.png)

#### IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING

**Comment by UtkarshGoel22** [comment]
I would like to work on this issue.

**Comment by karkranikhil** [comment]
I would like to work on this

**Comment by brittneypostma** [comment]
This looks to have been merged in, but is no longer in the project. This still needs to be added.

**Comment by khushali77** [comment]
Can I work on this?

**Comment by dabralyogesh** [comment]
Hey, Can I work on this?

**Comment by dabralyogesh** [comment]
@brittneypostma Is feature two already pushed? If not, then can I create a PR for this?

**Comment by brittneypostma** [comment]
@Utkarsh2604 was supposed to work on this originally. We will give 3 days from initial acceptance of issue to complete before handing off @dabralyogesh

**Comment by Utkarsh2604** [comment]
@brittneypostma I think there is some mistake,
I haven't been assigned any task.
I guess @UtkarshGoel22 is your guy.

**Comment by brittneypostma** [comment]
Ohhhhh, sorry about that. I see now, I tagged the wrong person :(

**Comment by UtkarshGoel22** [comment]
I think i already pushed feature two and it seemed to be merged. If it is not merged then should i make another pull request?

**Comment by khushali77** [comment]
If it isn't merged then can I take it up?

**Comment by brittneypostma** [comment]
Feature 2 is merged in. Closing this issue.
