### ISSUE TITLE
[CREATE] CHANGING THE TESTIMONIALS SECTION TO CAROUSEL 

### ISSUE THREAD

**Issue by Jappan07** [zero-to-mastery/Keiko-Corp#50]
Hello. Would it be a good idea to make the testimonials section as a sliding carousel @MattCSmith . If it would be fine, i would like to work on it.

**Comment by brittneypostma** [comment]
@Jappan07 this sounds interesting and there is no testimonial section implemented yet, go ahead and work on this.

**Comment by Jappan07** [comment]
@brittneypostma On it✌️

**Comment by Jappan07** [comment]
I am done with this feature and it is looking good. Please review my PR and merge this feature.
Thank You!

**Comment by brittneypostma** [comment]
@Jappan07 there is a checklist when you create a pr that looks like this:

![image](https://user-images.githubusercontent.com/45889730/94949404-ddfb8100-04ae-11eb-8b65-5cb81beff741.png)

It needs to be completed and link to this issue #50, try updating the pr
