### ISSUE TITLE
[FIX]NavBar not working properly in mobile view

### ISSUE THREAD

**Issue by arnabuchiha** [zero-to-mastery/Keiko-Corp#509]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

NavBar is not working properly in mobile view. It is transparent and not properly visible. CSS needs to be changed.

- [x] Change Background of NavBar Buttons
- [x] Change Background of NavBar Mobile View

![screenshot-keiko-corp netlify app-2020 10 06-00_35_33](https://user-images.githubusercontent.com/26869021/95120957-f946e480-076b-11eb-99c7-c6b892c81720.png)

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by SrirajBehera** [comment]
I want to work in this repository as to resolve this issue. Please assign me this issue. I will definitely put my best efforts forward.

**Comment by arnabuchiha** [comment]
This task is for me to complete as I marked it. @SrirajBehera Contribute in some other issue.
