### ISSUE TITLE
Page is not responsive in mobile view

### ISSUE THREAD

**Issue by Rishi-121** [zero-to-mastery/Keiko-Corp#524]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These PR's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[Page is not responsive in mobile view]

#### What is the task

The page must have to be responsive to the mobile view.

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by someone else'

**Comment by KryptonBD** [comment]
@Rishi-121 , Mobile view is done section by section, please check other issues, where it's already mentioned. Whoever responsible for specific section he'll do the responsive styling of that section.

**Comment by brittneypostma** [comment]
This will need to get done, but to avoid conflict Krypton is right. It should be done in each section.
