### ISSUE TITLE
[fix] Team Page and contact page in dark mode need to be fixed

### ISSUE THREAD

**Issue by Navdeepsingh4298** [zero-to-mastery/Keiko-Corp#543]
# New Task:

Fix styling in team page

## What is the task

while toggling dark mode, team page doesn't go in dark mode.
same problem in contact page.

![bandicam 2020-10-06 19-31-39-470](https://user-images.githubusercontent.com/65288518/95212578-78d7c080-080b-11eb-997c-51e90cdf44e6.jpg)

**Comment by madeinthearcade** [comment]
I can fix both pages @Navdeepsingh4298
