### ISSUE TITLE
[FIX] Text not aligned according to Mockup.

### ISSUE THREAD

**Issue by BhuvaneshPatil** [zero-to-mastery/Keiko-Corp#568]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:
![scrnli_10_7_2020_8-44-07 AM](https://user-images.githubusercontent.com/27822551/95283453-8166e000-0879-11eb-92f7-2af8004b3ff3.png)

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task
text is aligned in center but in the mockup it's aligned to left.
<Detail the problem/task>

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by readmey** [comment]
I could work on this.

**Comment by BhuvaneshPatil** [comment]
> I could work on this.

That's really great.. But I already fixed that and made a pull request..!!
Try and find more issues and fix them..!!
👍
