### ISSUE TITLE
Checkbox is visible in toggle button in contacts page

### ISSUE THREAD

**Issue by AmrutaKoshe** [zero-to-mastery/Keiko-Corp#576]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

This checkbox should not be visible when toggling through light and dark mode in the contacts page.
![image](https://user-images.githubusercontent.com/59871941/95307855-cfdea380-08a6-11eb-9df4-cee7a2315ab8.png)

![image](https://user-images.githubusercontent.com/59871941/95307900-dc62fc00-08a6-11eb-91ba-e57853d6700c.png)

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by paramaDEV** [comment]
Can I work in this?
