### ISSUE TITLE
[Fix]Company Section

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#582]
- Margins are not using css variables
- Colors are not according to mockup
- Dark mode colors are incorrect
![image](https://user-images.githubusercontent.com/45889730/95342560-8c277200-0885-11eb-9e17-db06d9e41ffc.png)
![image](https://user-images.githubusercontent.com/45889730/95342591-96e20700-0885-11eb-99c0-7dfcbb9bd2e2.png)

**Comment by khushali77** [comment]
Can I work on this issue?

**Comment by jomefavourite** [comment]
I'm too late...

**Comment by TaylorJonesTRT** [comment]
Has this been taken / actively being worked on?

**Comment by khushali77** [comment]
You can close this now, it's being done.

**Comment by arul-ashri** [comment]
assign this to me. I will do the necessary changes required.
