### ISSUE TITLE
[Fix] Testimonials Dark Mode

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#583]
Testimonial text disappears in dark mode.
![image](https://user-images.githubusercontent.com/45889730/95342702-b842f300-0885-11eb-9acc-6382a6f495ca.png)

**Comment by cessycode** [comment]
Hi @brittneypostma, I'd like to solve this bug. Can you please assign it to me?

**Comment by NinjaAniket** [comment]
Fixing it.
