### ISSUE TITLE
[Fix] Subscribe section Dark Mode

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#584]
The subscribe section does not change the icon and button color in dark mode.
![image](https://user-images.githubusercontent.com/45889730/95343117-28517900-0886-11eb-9bc7-12c6ddef25fd.png)

**Comment by Dhamodhar-DDR** [comment]
I'd like to work on it!

**Comment by khushali77** [comment]
Can I work on this issue?
