### ISSUE TITLE
[ CREATE ] - Feature 3

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Keiko-Corp#6]
Create feature three, as shown below. use a suitable image from Unsplash or similar (ensure its free to use)
add some interesting text or use a generator such as [ Pirate Ispum ](https://pirateipsum.me/) or [ Cupcake Ispum ](http://www.cupcakeipsum.com/)

![image](https://user-images.githubusercontent.com/6190356/94622493-37469300-02aa-11eb-8eb0-a16abb687c27.png)

#### IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING

**Comment by suman-nath** [comment]
working on this

**Comment by aayushi02agarwal** [comment]
I'm trying this

**Comment by khushali77** [comment]
Hi! Can I work on this?

**Comment by khushali77** [comment]
I have sent a pull request to this. Kindly check and merge it.

**Comment by brittneypostma** [comment]
Feature 3 has been implemented, closing issue.
