### ISSUE TITLE
[Fix]Styling of More dropdown

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#634]
- Remove background color on More
- Change background color to align with design using css variables. Find a color combo that works well.
- Add border radius to menu using variable.
![image](https://user-images.githubusercontent.com/45889730/95506647-2d91ef00-097e-11eb-9582-b05b2fbb84fb.png)

**Comment by leelatanniru** [comment]
@brittneypostma can i work on this issue?

**Comment by TaylorJonesTRT** [comment]
I can take this one!
