### ISSUE TITLE
[Fix]Footer stacking incorrectly 

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#636]
The footer should be either 4 across, 2 in a row, and then stack in a single column at mobile. Currently, it starts wrapping and has 3 on 1 line, which shouldn't happen. It will need to be reworked to be a single grid column at mobile, then 2 cols at a medium breakpoint, and finally a single flex row at the lg breakpoint.
![image](https://user-images.githubusercontent.com/45889730/95508502-1dc7da00-0981-11eb-9a6f-01772f5f5731.png)

**Comment by Khelthos** [comment]
I'll get this, ok?

**Comment by Khelthos** [comment]
So it is solved?
