### ISSUE TITLE
[Fix]Text Colors

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#653]
I need someone to review the colors and make sure we are using either the heading, text,  or lightBlue variables for all text. Only button text should use the red color.

**Comment by Yash7818** [comment]
may i work on this

**Comment by sandeep3136** [comment]
assign to me

**Comment by brittneypostma** [comment]
@Yash7818 I just assigned another issue to you. I am assigning @sandeep3136 to this one.

**Comment by abhishektanwar2001** [comment]
@brittneypostma i would love to do this one if possible please allow me have a look at this .

**Comment by sandeep3136** [comment]
@brittneypostma  could you make the issue more clear?

**Comment by Pranjal-bisht** [comment]
@brittneypostma i am interested. I am a complete newbie in open source knowing basics of html and CSS. can I start with this one?

**Comment by arul-ashri** [comment]
assign this issue to me.
