### ISSUE TITLE
[Fix]Dark Mode Colors

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#654]
Check all dark mode colors and make sure they align with the mockup and use the variables in global.css.
![image](https://user-images.githubusercontent.com/45889730/95583213-cae63500-0a09-11eb-978d-13bb796ef012.png)

**Comment by AmrutaKoshe** [comment]
sorry I won't be able to do this

**Comment by MostHegz** [comment]
Can I work on this?
