### ISSUE TITLE
Background of testimonial quote

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#655]
- Update the background of the testimonial quote to use the quote-box.svg

**Comment by TigerAsH94** [comment]
Can you be a little more specific please?
Do you mean to add the background to this element -> #testimonial-carousel .carousel-item ?

**Comment by brittneypostma** [comment]
![image](https://user-images.githubusercontent.com/45889730/95596944-07229100-0a1c-11eb-859d-235cabc5dc10.png)
The one above, should look like the one below using the quote-box.svg and layout correctly. 
![image](https://user-images.githubusercontent.com/45889730/95596967-0db10880-0a1c-11eb-819d-b64a5034f4b5.png)

**Comment by Yash7818** [comment]
may i work on this

**Comment by mynameispathak** [comment]
@brittneypostma Can I work on this?

**Comment by Yash7818** [comment]
@brittneypostma I am working on it

**Comment by Yash7818** [comment]
@brittneypostma I have updated the testimonial bg as per said

**Comment by brittneypostma** [comment]
![image](https://user-images.githubusercontent.com/45889730/95679680-77f3b580-0ba2-11eb-8e3c-52c6dcff990e.png)
Let's just use this, it will be easier to implement and look consisitent.

**Comment by Yash7818** [comment]
ok that to look good

**Comment by Yash7818** [comment]
@brittneypostma I have done the required changes

**Comment by brittneypostma** [comment]
@mynameispathak Do you still want a shot at this? I just merged in a change from Yash, but it still needs to use the css variables given in global.css. These are the specifications from the figma mockup.

**Comment by brittneypostma** [comment]
![image](https://user-images.githubusercontent.com/45889730/95690208-ee64d780-0be3-11eb-9abf-9eaf73c97dd6.png)

**Comment by mynameispathak** [comment]
@brittneypostma Yes please do assign it to me

**Comment by brittneypostma** [comment]
@mynameispathak you don't need to wait on an assignment from me. After 24 hours is given on an issue, you can take claim over it and send a pr.

**Comment by TaylorJonesTRT** [comment]
I know this has sorta of been adjusted with a recent PR but it doesn't really follow the design of the Figma mockup so I would love to finish this off and will submit a PR now!
