### ISSUE TITLE
[Fix] Show header on scroll

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#659]
A merge took this away and I think it should be implemented again.
- Show to header on scroll up.

**Comment by BhargaviChada** [comment]
I would like to work on this . Please do assign

**Comment by aal2015** [comment]
Hi brittneypostma, I am also interested working on it? Please assign it to me if no one is working on it.

**Comment by geeks5551** [comment]
this issue is looking interesting ? can I work on this ? could you assign me with this issue?

**Comment by MostHegz** [comment]
Can I work on this?
