### ISSUE TITLE
Going to create proper navbar

### ISSUE THREAD

**Issue by shubhdwiv12** [zero-to-mastery/Keiko-Corp#66]
I am going to work on creating proper navbar along with responsiveness.

**Comment by brittneypostma** [comment]
I'm not sure what you mean. Someone has already implemented a navbar, there was a fix pushed recently. Try updating your local copy.

**Comment by shubhdwiv12** [comment]
@brittneypostma  When i cloned the latest code, the navbar logo was not proper, and navbar links doesn't have proper naming such as Teams, testimonial along with contact button doesn't have proper style as per design pattern, i just implemented it accordingly, I am attaching the changes screenshot for your reference.
![image](https://user-images.githubusercontent.com/32597709/94854121-0a30e680-044a-11eb-830a-df7ebbbab7f2.png)

**Comment by brittneypostma** [comment]
Oh, I see what you mean. I will look at the pr.

**Comment by armedev** [comment]
@shubhdwiv12 plz link your PR. so that it can be merged else I will handle this issue.

**Comment by shubhdwiv12** [comment]
@armedev  i am doing it in a few moment as I was in talk with @brittneypostma , request you to take another issue.
