### ISSUE TITLE
[Fix] Pricing section button

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#670]
I love the new addition of the text under the price, but I think the button does not fit with the design. Try using the variable heading color with the lightBlue text color.
![image](https://user-images.githubusercontent.com/45889730/95655929-bd4bb080-0ad8-11eb-840b-9fde9e252faa.png)

**Comment by debPhoenix** [comment]
Hello! I'm addind style to the section button!

**Comment by geeks5551** [comment]
hey can i work on this issue?

**Comment by brittneypostma** [comment]
I think no border on the button, more like the one below. Going to update the mockup too.
![image](https://user-images.githubusercontent.com/45889730/95689792-52d26780-0be1-11eb-84f9-8af56faeca7d.png)

**Comment by khushali77** [comment]
Can I work on this?

**Comment by debPhoenix** [comment]
> I think no border on the button, more like the one below. Going to update the mockup too.
> ![image](https://user-images.githubusercontent.com/45889730/95689792-52d26780-0be1-11eb-84f9-8af56faeca7d.png)

Ok, and the hover button?

**Comment by brittneypostma** [comment]
@debPhoenix The hover I used is the text color, gray with lightBlue for the Sign Up.

**Comment by gdhebling** [comment]
Hi, I would like to work on these issues from Sign Up buttons:
- [ ] Remove red border
- [ ] Fix alignment
- [ ] Alter hover effect to lightBlue instead of Red
![image](https://user-images.githubusercontent.com/62028115/96468408-5f337180-122c-11eb-9772-de8f1e24d08b.png)
