### ISSUE TITLE
Footer About Us Section

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#673]
- Remove text in red square
![image](https://user-images.githubusercontent.com/45889730/95656095-f0427400-0ad9-11eb-9542-902c5e4547f8.png)

**Comment by mynameispathak** [comment]
@brittneypostma Assign this to me.

**Comment by YatharthVyas** [comment]
@brittneypostma I would like to contribute to this

**Comment by SriCoD** [comment]
can i please work on this, do assign this to me. I'm enthusiastic to work on it
