### ISSUE TITLE
Navigation Bar overlap at a certain device width

### ISSUE THREAD

**Issue by MostHegz** [zero-to-mastery/Keiko-Corp#680]
# New Task:

#### What is the task

At certain width the Navigation bar buttons start appearing on top of each other
![image](https://user-images.githubusercontent.com/67126299/95660678-b1d4a580-0b29-11eb-81d7-311fc96227e9.png)

### Who is the task for?

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

**Comment by MostHegz** [comment]
I'd like to add that this issue doesn't occur on chrome. I can only see it using firefox.

**Comment by MostHegz** [comment]
@brittneypostma Can you please add the "hacktoberfest" label if this is eligible for it?

**Comment by brittneypostma** [comment]
The repo has the label on it, so it isn't needed, but I added it. This overlap is actually a problem with the whole navbar itself. I noticed on the smallest viewport (320px) that it was getting smaller in width when scrolled and some links don't work. Then, if you go to other pages the dark/light mode may not even work at all. It looks very inconsistent.

**Comment by MostHegz** [comment]
yeah, thanks for letting me notice this. I'll try to fix the positioning of the navbar. I just want to know what the required design is 
should it be small and to the left like this (of course without the buggy toggle button):
![image](https://user-images.githubusercontent.com/67126299/95718838-472d8200-0c6f-11eb-97d0-d91dde17647b.png)
or should it stay the same size as it was on the top of the page?
![image](https://user-images.githubusercontent.com/67126299/95718955-76dc8a00-0c6f-11eb-8af7-098f717c8da6.png)

**Comment by MostHegz** [comment]
As for the Dark Mode for other pages I'll create an issue for it. 
Additionally I think in one of the accepted pull requests the toggle button doesn't change its color in Dark mode anymore. I'll fix that as well.
