### ISSUE TITLE
Contact-Us page navbar

### ISSUE THREAD

**Issue by amnon3234** [zero-to-mastery/Keiko-Corp#685]
#### What is the task

In the contact us page, the navbar buttons remain black after switching to dark mode.

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [X] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

- [X] I have looked at all the issues currently available and this does not exist or overlap with another ticket

**Comment by SMD-1** [comment]
@amnon3234 I would like to work on this, please do assign

**Comment by amnon3234** [comment]
Hi allready fixed the problem :) and sent a pull request with the solution. However I notice tons of issues in the login page that I didn't have time to submit. You can go and find somthing to do there for sure.

Good luck @SMD-1

**Comment by SMD-1** [comment]
@amnon3234 yeah there is lot to do with login page, thanks 👍

**Comment by tranjenny** [comment]
can i try?

**Comment by SMD-1** [comment]
@tranjenny it's already assigned
