### ISSUE TITLE
Duplicate assets files in the code

### ISSUE THREAD

**Issue by Kaku-g** [zero-to-mastery/Keiko-Corp#696]
The two assets files having same folder and files are creating confusion while fixing the issue.

**Comment by Tanish2207** [comment]
I also faced the same issue, but when I try to Delete the duplicated one, the layout of site is changed.

**Comment by kofosu2289** [comment]
I tried to fix this issue locally and there is no layout issue on my end. I'm going to try and open a pull request to resolve this issue
