### ISSUE TITLE
[ CREATE ] - Email Call to Action

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Keiko-Corp#7]
Create the email subscription section as shown below: 

![image](https://user-images.githubusercontent.com/6190356/94622595-665d0480-02aa-11eb-8eac-36d42ecefd24.png)

#### IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING

**Comment by Apoorve73** [comment]
I would love to work on this!

**Comment by Jappan07** [comment]
> I would love to work on this!

Are you still working on this?

**Comment by Apoorve73** [comment]
Yes! Can I ?

**Comment by Jappan07** [comment]
Ok no worries go ahead if you are already working.

**Comment by brittneypostma** [comment]
@Apoorve73 This section is done except for the input, submit button, and to make the bottom line bold and italic. Are  you still working on these?

**Comment by Apoorve73** [comment]
Yes! I will pull the changes.

**Comment by Apoorve73** [comment]
@MattCSmith or @Jappan07 or @brittneypostma , Please let me know, with what name should I create a new section in navbar.
Also, I can't see this section as described here:


> @Apoorve73 This section is done except for the input, submit button, and to make the bottom line bold and italic. Are you still working on these?

**Comment by brittneypostma** [comment]
I don't know what you mean by a new section in the navbar. This is for the Call to Action section in red here:
![image](https://user-images.githubusercontent.com/45889730/94923957-af6baf00-048a-11eb-8b9a-caa75605e605.png)

If you are working on another issue, please make a new branch for that after this one is complete.

**Comment by Apoorve73** [comment]
Sure thing Ma'am! What I want to ask is, I will add this, but is the above part done? 
I.e. Never Miss an update.(continued)..blind texts.

**Comment by Apoorve73** [comment]
![Screenshot from 2020-10-02 19-17-20](https://user-images.githubusercontent.com/55204045/94930370-ecb05b00-04e3-11eb-81c0-56ee8745bc35.png)
Is is okay?

**Comment by Apoorve73** [comment]
![Screenshot from 2020-10-02 19-23-38](https://user-images.githubusercontent.com/55204045/94931016-dd7ddd00-04e4-11eb-9a40-0c719b0b255f.png)

Is it okay?

**Comment by brittneypostma** [comment]
@Apoorve73 the screenshot is fine, but the issue needs to be linked to the pr for it to be merged in.

**Comment by Apoorve73** [comment]
Sure thing! I will do that!

**Comment by Apoorve73** [comment]
@brittneypostma Kindly check PR #239
