### ISSUE TITLE
hover effect in nav bar dark mode

### ISSUE THREAD

**Issue by AmrutaKoshe** [zero-to-mastery/Keiko-Corp#700]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

In the more dropdown, there should be a hover effect on the elements in the dark mode like how it is in light mode. Also on the contact and login buttons.
![image](https://user-images.githubusercontent.com/59871941/95684068-98f0f080-0c0c-11eb-908e-46f36c276961.png)

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [ ] I created this task for me to complete, I will create a PR soon.
- [x] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by theenthusiastprogrammer** [comment]
Hey, I think I can fix this hover issue.

**Comment by AmrutaKoshe** [comment]
> Hey, I think I can fix this hover issue.

okay!

**Comment by theenthusiastprogrammer** [comment]
Can you assign this task to me?

**Comment by theenthusiastprogrammer** [comment]
> > Hey, I think I can fix this hover issue.C

> > Hey, I think I can fix this hover issue.
> 
> okay!

Can you assign this task to me?

**Comment by theenthusiastprogrammer** [comment]
> > Hey, I think I can fix this hover issue.
> 
> okay!

Can you assign this task to me?

**Comment by faraz16iqbal** [comment]
Is this task still open?
