### ISSUE TITLE
[CREATE] - favicon.ico for index.htm home page

### ISSUE THREAD

**Issue by Guitarhub786** [zero-to-mastery/Keiko-Corp#71]
Create favicon.ico for index.htm home page. @MattCSmith

**Comment by Guitarhub786** [comment]
If you accept, I will like to allocate and take on this task. - Guitarhub786

**Comment by heet-vakharia** [comment]
Can I Do it?

**Comment by Surya742** [comment]
I am working on it.

**Comment by Surya742** [comment]
Work Done, I made a PR.

**Comment by MattCSmith** [comment]
In the pursuit of fairness, @Guitarhub786 created the ticket and requested the task, I think its only fair that they are able to complete it. I am going to close the PR 87. 

Feel free to create your PR for this task @Guitarhub786

**Comment by brittneypostma** [comment]
I believe this has been taken care of. Closing the issue.
