### ISSUE TITLE
Get started button should link to pricing section

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#753]
- make call to action button link to pricing
![image](https://user-images.githubusercontent.com/45889730/95991331-a4a20a00-0dfa-11eb-8002-787ff157f942.png)

**Comment by slytherin20** [comment]
Hi @brittneypostma,
Can I work on this issue?

**Comment by aal2015** [comment]
Hi @brittneypostma, I would also like to work in this issue?
