### ISSUE TITLE
[Fix] Navbar overhaul

### ISSUE THREAD

**Issue by brittneypostma** [zero-to-mastery/Keiko-Corp#755]
The Navbar has a lot of issues. It overlaps at some widths and the team link disappears at breakpoints.
- Add a consistent responsive flow to the header/navbar
- Make sure all links show at all widths, even if they go into the dropdown
- Fix mobile navigation
![image](https://user-images.githubusercontent.com/45889730/95991707-1aa67100-0dfb-11eb-86cd-8c3360fcaa5a.png)

**Comment by mhkasif** [comment]
Hi ma'am , I would like to work on this issue.
I will be thankful if you assign this to me.
Thanks

**Comment by aal2015** [comment]
Hi @brittneypostma, i would also like to work in this issue.

**Comment by krdormer** [comment]
@brittneypostma I would also like to work on this if possible

**Comment by Neurum** [comment]
I would like to work on this issue.
