### ISSUE TITLE
'Home' link needs to be white in dark mode

### ISSUE THREAD

**Issue by KirstenBolda** [zero-to-mastery/Keiko-Corp#774]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

'Home' link in dark mode needs to be white as it is shown in the mockup and to match the other nav items (Features, Testimonial, Team and More)
![image](https://user-images.githubusercontent.com/19215943/96073383-f9ca3400-0e6b-11eb-9900-0d50ceda1251.png)
![image](https://user-images.githubusercontent.com/19215943/96073408-02bb0580-0e6c-11eb-970d-6d53d2712938.png)

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by yashbansal130** [comment]
@KirstenBolda I would like to work on this issue

**Comment by KirstenBolda** [comment]
@yashbansal130 Sure, have at it!
I know I had indicated that I would create the PR, but since it's been two days, feel free to tackle it. I'll be interested to see what you come up with.
Happy coding!

**Comment by yashbansal130** [comment]
@KirstenBolda I am on it . thanks
