### ISSUE TITLE
Adding flipping over effect on price cards on hover  and and transition effect to the testimonial cards

### ISSUE THREAD

**Issue by paullaster** [zero-to-mastery/Keiko-Corp#778]
_#_ New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task
On the website when clients get to the price cards,
![cost-section](https://user-images.githubusercontent.com/43445963/96104230-40a64100-0ee1-11eb-9a0b-77ab9371da80.PNG)
The card front should only display package e.g. Enterprise and price and when hover for large devices on focus for mobile devices it should flip the back having other details and  plus the sign up button.

The testimonial cards should be transitioning or coming upward on hover in large screens and on focus for mobile devices.
  
![testimonial](https://user-images.githubusercontent.com/43445963/96105798-1ce3fa80-0ee3-11eb-861e-2742652f2ebd.PNG)

### Who is the task for?
 Create animation effect on the testimonial cards and the price cards in the cost section
[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by paullaster** [comment]
May Tackle this issue.

**Comment by brittneypostma** [comment]
This is going to conflict with issue #766, you should comment over there to add this. I'm not against it, the current styling is not correct, but I don't want conflicting pr's.
