### ISSUE TITLE
Fix Keiko Button on Contact Us page to go Home

### ISSUE THREAD

**Issue by SimulatedPanda** [zero-to-mastery/Keiko-Corp#786]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # Keiko button on Contact Us page does not return user to home

#### What is the task

<Detail the problem/task>

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by shazm12** [comment]
Hi, I would like to work on this issue.

**Comment by SimulatedPanda** [comment]
Hi there. I think I've actually already resolved it. Though there is a typo in my code, which I will fix once the PR is accepted (I missed the / before the a to close the href)

**Comment by shazm12** [comment]
okay np
