### ISSUE TITLE
[ CREATE ] - Testimonial Section

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Keiko-Corp#8]
Create the testimonial section as picture below: 
![image](https://user-images.githubusercontent.com/6190356/94622781-b936bc00-02aa-11eb-9e31-e5b829863a8b.png)

#### IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING

**Comment by Ac-Srikanth** [comment]
I can work on this

**Comment by JamiuJimoh** [comment]
Can I work on this?

**Comment by comebackid87** [comment]
Please may I work on the task as well.

**Comment by brittneypostma** [comment]
This is implemented except for the svg background if you want to take a shot at that @Ac-Srikanth

**Comment by Ac-Srikanth** [comment]
@brittneypostma , sure i will give it a try

**Comment by brittneypostma** [comment]
@Ac-Srikanth can you provide an update on the svg? Are you able to provide a pull request today?

**Comment by Ac-Srikanth** [comment]
@brittneypostma i tried but not able to do it , but what I see is the testimonial section is far from complete , or is it the completed version is not merged yet?

**Comment by brittneypostma** [comment]
I'm sorry,  we just updated the site and are no longer using this.  I'll close the issue.
