### ISSUE TITLE
Hover state not signified

### ISSUE THREAD

**Issue by jomefavourite** [zero-to-mastery/Keiko-Corp#806]
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

Hovering over the button isn't showing significant the background colour is the same
![scrnli_10_17_2020_7-27-05 PM](https://user-images.githubusercontent.com/54733225/96350872-c11a9c80-10af-11eb-924d-a7f3ae220fc5.png)

<Detail the problem/task>

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [ ] I created this task for me to complete, I will create a PR soon.
- [x] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by WayneMacMavis** [comment]
Could i give this task a try?

**Comment by jomefavourite** [comment]
I see you've already done it, let's wait for it to be merged.

**Comment by brittneypostma** [comment]
@jomefavourite I think they claimed it because you marked it for someone else to claim, if you want to do them yourself just mark the other box.

**Comment by jomefavourite** [comment]
I actually wanted someone else to do it @brittneypostma

**Comment by WayneMacMavis** [comment]
Well thank you for giving me something to do @jomefavourite :-) I've been trying to get a task to do for quite some time. But there's always someone that beats me to the punch.

**Comment by jomefavourite** [comment]
No problem @WayneMacMavis
