### ISSUE TITLE
Rest of Contact Section

### ISSUE THREAD

**Issue by Dan-Y-Ko** [zero-to-mastery/Keiko-Corp#82]
Reference: https://i.imgur.com/zulEMfr.png

**Comment by Dan-Y-Ko** [comment]
I completed #89 which is only for markup. Feel free to finish the styling portion.

**Comment by frantic32211** [comment]
@Dan-Y-Ko  Can I work on the styling portion?

**Comment by chetas411** [comment]
@Dan-Y-Ko  there is already Contact Us page linked,  I guess there is no need for this now.
https://keiko-corp.netlify.app/contact.html

**Comment by brittneypostma** [comment]
Leaving this open. This section still needs to be completed. 
![image](https://user-images.githubusercontent.com/45889730/94927006-a92c0180-048f-11eb-87b2-1a91479b18f8.png)

**Comment by chetas411** [comment]
> 
> 
> Leaving this open. This section still needs to be completed.
@brittneypostma  can you review this one ? #131

**Comment by brittneypostma** [comment]
Closing this issue to merge with #199
