### ISSUE TITLE
[ CREATE ] - Meet the team

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/Keiko-Corp#9]
Create the meet the team section as detailed in the image below: 

![image](https://user-images.githubusercontent.com/6190356/94623048-424df300-02ab-11eb-9be4-e6d6045be053.png)

#### IF YOU WISH TO WORK ON THIS, PLEASE CHECK NO ONE HAS CLAIMED IT BELOW, IF NOT CLAIM IT BY COMMENTING

**Comment by rachelktyjohnson** [comment]
Hello! I would like to claim this by commenting. Super keen to work on this!
