### ISSUE TITLE
Issue in query selector on login page and script.js

### ISSUE THREAD

**Issue by ps011** [zero-to-mastery/Keiko-Corp#925]
# New Task:
[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

Fix a query selector issue on login page

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [ x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x ] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by Fuglydami** [comment]
I'll like to claim this task, as this will be my first pull request

**Comment by brittneypostma** [comment]
This actually isn't a needed fix. It is correct as it was, shown below in the [MDN example](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById).

![image](https://user-images.githubusercontent.com/45889730/97096220-de62e400-1636-11eb-8248-123749dc4dd3.png)
